import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../../data/models/sermon_model.dart';

/// Generates a clean, publication-quality PDF from a [Sermon] and opens the
/// native share / print sheet via the `printing` package.
class SermonExportService {
  // ── Brand colours ──────────────────────────────────────────────────────────
  // Warm gold — matches the default PulpitFlow accent (#C9A84C)
  static const _accent = PdfColor(0.788, 0.659, 0.298);
  static const _accentLight = PdfColor(0.98, 0.965, 0.91); // cream tint
  static const _accentText = PdfColor(0.45, 0.31, 0.04);
  static const _bodyText = PdfColor(0.1, 0.1, 0.1);
  static const _subtleText = PdfColor(0.45, 0.45, 0.45);
  static const _divider = PdfColor(0.82, 0.82, 0.82);

  // ── Public entry point ─────────────────────────────────────────────────────
  static Future<void> exportToPdf(Sermon sermon) async {
    final doc = pw.Document(
      title: sermon.title,
      author: 'PulpitFlow',
      creator: 'PulpitFlow — Sermon Preparation App',
    );

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(64, 56, 64, 56),
        header: (ctx) => _header(sermon, ctx),
        footer: (ctx) => _footer(ctx),
        build: (ctx) => [
          _titleBlock(sermon),
          pw.SizedBox(height: 28),
          ..._contentBlocks(sermon),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => doc.save(),
      name: _safeFilename(sermon.title),
    );
  }

  // ── Header (every page) ────────────────────────────────────────────────────
  static pw.Widget _header(Sermon sermon, pw.Context ctx) {
    // Skip the branded header on the first page — the title block handles it.
    if (ctx.pageNumber == 1) return pw.SizedBox();
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'PulpitFlow',
              style: pw.TextStyle(
                font: pw.Font.timesBold(),
                fontSize: 9,
                color: _accent,
                letterSpacing: 1.4,
              ),
            ),
            pw.Text(
              sermon.title,
              style: pw.TextStyle(
                font: pw.Font.helveticaOblique(),
                fontSize: 9,
                color: _subtleText,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 4),
        pw.Divider(color: _divider, thickness: 0.5),
        pw.SizedBox(height: 10),
      ],
    );
  }

  // ── Footer (every page) ────────────────────────────────────────────────────
  static pw.Widget _footer(pw.Context ctx) {
    return pw.Column(
      children: [
        pw.SizedBox(height: 6),
        pw.Divider(color: _divider, thickness: 0.5),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by PulpitFlow · ${DateFormat('MMM d, y').format(DateTime.now())}',
              style: pw.TextStyle(
                font: pw.Font.helvetica(),
                fontSize: 8,
                color: _subtleText,
              ),
            ),
            pw.Text(
              'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: pw.TextStyle(
                font: pw.Font.helvetica(),
                fontSize: 8,
                color: _subtleText,
              ),
            ),
          ],
        ),
      ],
    );
  }

  // ── Title block ────────────────────────────────────────────────────────────
  static pw.Widget _titleBlock(Sermon sermon) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        // App label
        pw.Text(
          'PULPITFLOW',
          style: pw.TextStyle(
            font: pw.Font.helveticaBold(),
            fontSize: 8,
            color: _accent,
            letterSpacing: 2.5,
          ),
        ),
        pw.SizedBox(height: 10),
        // Sermon title
        pw.Text(
          sermon.title,
          style: pw.TextStyle(
            font: pw.Font.timesBold(),
            fontSize: 30,
            color: _bodyText,
            lineSpacing: 3,
          ),
        ),
        pw.SizedBox(height: 10),
        // Gold underline accent
        pw.Container(width: 56, height: 3, color: _accent),
        pw.SizedBox(height: 12),
        // Series tag (if set)
        if (sermon.series != null && sermon.series!.isNotEmpty) ...[
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
            decoration: pw.BoxDecoration(
              color: _accentLight,
              border: pw.Border.all(color: _accent, width: 0.8),
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Text(
              'Series: ${sermon.series}',
              style: pw.TextStyle(
                font: pw.Font.helveticaBold(),
                fontSize: 10,
                color: _accentText,
              ),
            ),
          ),
          pw.SizedBox(height: 10),
        ],
        // Tags row (if any)
        if (sermon.tags.isNotEmpty) ...[
          pw.Wrap(
            spacing: 6,
            runSpacing: 4,
            children: sermon.tags
                .map(
                  (tag) => pw.Container(
                    padding: const pw.EdgeInsets.symmetric(
                      horizontal: 8,
                      vertical: 3,
                    ),
                    decoration: pw.BoxDecoration(
                      color: const PdfColor(0.94, 0.94, 0.94),
                      borderRadius: pw.BorderRadius.circular(4),
                    ),
                    child: pw.Text(
                      tag,
                      style: pw.TextStyle(
                        font: pw.Font.helvetica(),
                        fontSize: 9,
                        color: _subtleText,
                      ),
                    ),
                  ),
                )
                .toList(),
          ),
          pw.SizedBox(height: 10),
        ],
        // Metadata line
        pw.Text(
          _metaLine(sermon),
          style: pw.TextStyle(
            font: pw.Font.helvetica(),
            fontSize: 10,
            color: _subtleText,
          ),
        ),
        pw.SizedBox(height: 20),
        pw.Divider(color: _divider, thickness: 0.5),
      ],
    );
  }

  // ── Content blocks ─────────────────────────────────────────────────────────
  static List<pw.Widget> _contentBlocks(Sermon sermon) {
    final widgets = <pw.Widget>[];
    for (final block in sermon.blocks) {
      if (block.type == BlockType.text) {
        final text = block.content.trim();
        if (text.isEmpty) continue;
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 14),
            child: pw.Text(
              text,
              style: pw.TextStyle(
                font: pw.Font.times(),
                fontSize: 13,
                color: _bodyText,
                lineSpacing: 5,
                height: 1.5,
              ),
            ),
          ),
        );
      } else {
        // Scripture chip
        final ref = block.scriptureRef ?? block.content;
        final translation = block.translation ?? sermon.defaultTranslation;
        widgets.add(_scriptureChip(ref, translation));
      }
    }

    // Reflection notes (if present)
    if (sermon.notes != null && sermon.notes!.isNotEmpty) {
      widgets.addAll([
        pw.SizedBox(height: 24),
        pw.Divider(color: _divider, thickness: 0.5),
        pw.SizedBox(height: 14),
        pw.Text(
          'REFLECTION NOTES',
          style: pw.TextStyle(
            font: pw.Font.helveticaBold(),
            fontSize: 8,
            color: _accent,
            letterSpacing: 2.0,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Container(
          padding: const pw.EdgeInsets.all(14),
          decoration: pw.BoxDecoration(
            color: _accentLight,
            borderRadius: pw.BorderRadius.circular(6),
            border: pw.Border.all(color: _accent, width: 0.6),
          ),
          child: pw.Text(
            sermon.notes!,
            style: pw.TextStyle(
              font: pw.Font.timesItalic(),
              fontSize: 12,
              color: _bodyText,
              lineSpacing: 4,
              height: 1.5,
            ),
          ),
        ),
      ]);
    }

    return widgets;
  }

  static pw.Widget _scriptureChip(String ref, String translation) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 8),
      child: pw.Container(
        padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 10),
        decoration: pw.BoxDecoration(
          color: _accentLight,
          border: pw.Border(left: pw.BorderSide(color: _accent, width: 3)),
          borderRadius: pw.BorderRadius.only(
            topRight: const pw.Radius.circular(6),
            bottomRight: const pw.Radius.circular(6),
          ),
        ),
        child: pw.Row(
          children: [
            pw.Expanded(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    ref,
                    style: pw.TextStyle(
                      font: pw.Font.timesBold(),
                      fontSize: 13,
                      color: _accentText,
                    ),
                  ),
                  pw.SizedBox(height: 2),
                  pw.Text(
                    translation,
                    style: pw.TextStyle(
                      font: pw.Font.helvetica(),
                      fontSize: 9,
                      color: _subtleText,
                      letterSpacing: 0.5,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ── Helpers ────────────────────────────────────────────────────────────────
  static String _metaLine(Sermon sermon) {
    final parts = <String>[];
    parts.add(sermon.defaultTranslation);
    final sc = sermon.scriptureCount;
    if (sc > 0) parts.add('$sc scripture ref${sc == 1 ? '' : 's'}');
    switch (sermon.status) {
      case SermonStatus.draft:
        parts.add('Draft');
        break;
      case SermonStatus.ready:
        parts.add('Ready to Preach');
        break;
      case SermonStatus.preached:
        parts.add('Preached ${DateFormat('MMM d, y').format(sermon.updatedAt)}');
        break;
    }
    return parts.join(' · ');
  }

  static String _safeFilename(String title) {
    final safe = title.replaceAll(RegExp(r'[^\w\s\-]'), '').trim();
    return '${safe.isEmpty ? 'Sermon' : safe}.pdf';
  }
}
